version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 115998231330.dkr.ecr.us-east-1.amazonaws.com
      - echo "Checking for existing repository..."
      - aws ecr describe-repositories --repository-names springboot-app || aws ecr create-repository --repository-name springboot-app
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo "Preparing to build with tag: $IMAGE_TAG"

  build:
    commands:
      - echo "Build started on `date`"
      - echo "Building Spring Boot application..."
      - ./mvnw clean package -DskipTests
      - echo "Building Docker image..."
      - docker build -t 115998231330.dkr.ecr.us-east-1.amazonaws.com/springboot-app:$IMAGE_TAG .
      - docker tag 115998231330.dkr.ecr.us-east-1.amazonaws.com/springboot-app:$IMAGE_TAG 115998231330.dkr.ecr.us-east-1.amazonaws.com/springboot-app:latest

  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Pushing Docker images..."
      - docker push 115998231330.dkr.ecr.us-east-1.amazonaws.com/springboot-app:$IMAGE_TAG
      - docker push 115998231330.dkr.ecr.us-east-1.amazonaws.com/springboot-app:latest
      - echo "Creating image definitions file for ECS..."
      - printf '[{"name":"springboot-app","imageUri":"%s"}]' 115998231330.dkr.ecr.us-east-1.amazonaws.com/springboot-app:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files: imagedefinitions.json
