version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Installing dependencies..."
      - apt-get update -y && apt-get install -y maven
      - mvn --version

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 115998231330.dkr.ecr.us-east-1.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}

  build:
    commands:
      - echo "Building Spring Boot application..."
      - mvn clean package -DskipTests
      - echo "Building Docker image..."
      - docker build -t 115998231330.dkr.ecr.us-east-1.amazonaws.com/springboot-app:$IMAGE_TAG .
      - docker tag 115998231330.dkr.ecr.us-east-1.amazonaws.com/springboot-app:$IMAGE_TAG 115998231330.dkr.ecr.us-east-1.amazonaws.com/springboot-app:latest

  post_build:
    commands:
      - echo "Pushing Docker image..."
      - docker push 115998231330.dkr.ecr.us-east-1.amazonaws.com/springboot-app:$IMAGE_TAG
      - docker push 115998231330.dkr.ecr.us-east-1.amazonaws.com/springboot-app:latest
      - printf '[{"name":"springboot-app","imageUri":"%s"}]' 115998231330.dkr.ecr.us-east-1.amazonaws.com/springboot-app:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files: imagedefinitions.json
